<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\ProvisioningOptions;

use UnexpectedValueException;

/**
 * Protobuf type <code>VideoWidevineServer.SDK.ProvisioningOptions.CertificateType</code>
 */
class CertificateType
{
    /**
     * Default.  The original certificate type.
     *
     * Generated from protobuf enum <code>WIDEVINE_DRM = 0;</code>
     */
    const WIDEVINE_DRM = 0;
    /**
     * X.509 certificate.
     *
     * Generated from protobuf enum <code>X509 = 1;</code>
     */
    const X509 = 1;

    private static $valueToName = [
        self::WIDEVINE_DRM => 'WIDEVINE_DRM',
        self::X509 => 'X509',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(CertificateType::class, \VideoWidevineServer\SDK\ProvisioningOptions_CertificateType::class);

