<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\ClientIdentification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Capabilities which not all clients may support. Used for the license
 * exchange protocol only.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities</code>
 */
class ClientCapabilities extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool client_token = 1;</code>
     */
    protected $client_token = null;
    /**
     * Generated from protobuf field <code>optional bool session_token = 2;</code>
     */
    protected $session_token = null;
    /**
     * Generated from protobuf field <code>optional bool video_resolution_constraints = 3;</code>
     */
    protected $video_resolution_constraints = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities.HdcpVersion max_hdcp_version = 4;</code>
     */
    protected $max_hdcp_version = null;
    /**
     * Generated from protobuf field <code>optional uint32 oem_crypto_api_version = 5;</code>
     */
    protected $oem_crypto_api_version = null;
    /**
     * Generated from protobuf field <code>optional bool anti_rollback_usage_table = 6;</code>
     */
    protected $anti_rollback_usage_table = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $client_token
     *     @type bool $session_token
     *     @type bool $video_resolution_constraints
     *     @type int $max_hdcp_version
     *     @type int $oem_crypto_api_version
     *     @type bool $anti_rollback_usage_table
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool client_token = 1;</code>
     * @return bool
     */
    public function getClientToken()
    {
        return isset($this->client_token) ? $this->client_token : false;
    }

    public function hasClientToken()
    {
        return isset($this->client_token);
    }

    public function clearClientToken()
    {
        unset($this->client_token);
    }

    /**
     * Generated from protobuf field <code>optional bool client_token = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setClientToken($var)
    {
        GPBUtil::checkBool($var);
        $this->client_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool session_token = 2;</code>
     * @return bool
     */
    public function getSessionToken()
    {
        return isset($this->session_token) ? $this->session_token : false;
    }

    public function hasSessionToken()
    {
        return isset($this->session_token);
    }

    public function clearSessionToken()
    {
        unset($this->session_token);
    }

    /**
     * Generated from protobuf field <code>optional bool session_token = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setSessionToken($var)
    {
        GPBUtil::checkBool($var);
        $this->session_token = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool video_resolution_constraints = 3;</code>
     * @return bool
     */
    public function getVideoResolutionConstraints()
    {
        return isset($this->video_resolution_constraints) ? $this->video_resolution_constraints : false;
    }

    public function hasVideoResolutionConstraints()
    {
        return isset($this->video_resolution_constraints);
    }

    public function clearVideoResolutionConstraints()
    {
        unset($this->video_resolution_constraints);
    }

    /**
     * Generated from protobuf field <code>optional bool video_resolution_constraints = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setVideoResolutionConstraints($var)
    {
        GPBUtil::checkBool($var);
        $this->video_resolution_constraints = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities.HdcpVersion max_hdcp_version = 4;</code>
     * @return int
     */
    public function getMaxHdcpVersion()
    {
        return isset($this->max_hdcp_version) ? $this->max_hdcp_version : 0;
    }

    public function hasMaxHdcpVersion()
    {
        return isset($this->max_hdcp_version);
    }

    public function clearMaxHdcpVersion()
    {
        unset($this->max_hdcp_version);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities.HdcpVersion max_hdcp_version = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxHdcpVersion($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities\HdcpVersion::class);
        $this->max_hdcp_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 oem_crypto_api_version = 5;</code>
     * @return int
     */
    public function getOemCryptoApiVersion()
    {
        return isset($this->oem_crypto_api_version) ? $this->oem_crypto_api_version : 0;
    }

    public function hasOemCryptoApiVersion()
    {
        return isset($this->oem_crypto_api_version);
    }

    public function clearOemCryptoApiVersion()
    {
        unset($this->oem_crypto_api_version);
    }

    /**
     * Generated from protobuf field <code>optional uint32 oem_crypto_api_version = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOemCryptoApiVersion($var)
    {
        GPBUtil::checkUint32($var);
        $this->oem_crypto_api_version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool anti_rollback_usage_table = 6;</code>
     * @return bool
     */
    public function getAntiRollbackUsageTable()
    {
        return isset($this->anti_rollback_usage_table) ? $this->anti_rollback_usage_table : false;
    }

    public function hasAntiRollbackUsageTable()
    {
        return isset($this->anti_rollback_usage_table);
    }

    public function clearAntiRollbackUsageTable()
    {
        unset($this->anti_rollback_usage_table);
    }

    /**
     * Generated from protobuf field <code>optional bool anti_rollback_usage_table = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setAntiRollbackUsageTable($var)
    {
        GPBUtil::checkBool($var);
        $this->anti_rollback_usage_table = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ClientCapabilities::class, \VideoWidevineServer\SDK\ClientIdentification_ClientCapabilities::class);

