<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\ClientIdentification;

use UnexpectedValueException;

/**
 * Protobuf type <code>VideoWidevineServer.SDK.ClientIdentification.TokenType</code>
 */
class TokenType
{
    /**
     * Generated from protobuf enum <code>KEYBOX = 0;</code>
     */
    const KEYBOX = 0;
    /**
     * Generated from protobuf enum <code>DEVICE_CERTIFICATE = 1;</code>
     */
    const DEVICE_CERTIFICATE = 1;
    /**
     * Generated from protobuf enum <code>REMOTE_ATTESTATION_CERTIFICATE = 2;</code>
     */
    const REMOTE_ATTESTATION_CERTIFICATE = 2;

    private static $valueToName = [
        self::KEYBOX => 'KEYBOX',
        self::DEVICE_CERTIFICATE => 'DEVICE_CERTIFICATE',
        self::REMOTE_ATTESTATION_CERTIFICATE => 'REMOTE_ATTESTATION_CERTIFICATE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TokenType::class, \VideoWidevineServer\SDK\ClientIdentification_TokenType::class);

