<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\ProvisionedDeviceInfo;

use UnexpectedValueException;

/**
 * Protobuf type <code>VideoWidevineServer.SDK.ProvisionedDeviceInfo.WvSecurityLevel</code>
 */
class WvSecurityLevel
{
    /**
     * Defined in "WV Modular DRM Security Integration Guide for
     * Common Encryption (CENC)"
     *
     * Generated from protobuf enum <code>LEVEL_UNSPECIFIED = 0;</code>
     */
    const LEVEL_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>LEVEL_1 = 1;</code>
     */
    const LEVEL_1 = 1;
    /**
     * Generated from protobuf enum <code>LEVEL_2 = 2;</code>
     */
    const LEVEL_2 = 2;
    /**
     * Generated from protobuf enum <code>LEVEL_3 = 3;</code>
     */
    const LEVEL_3 = 3;

    private static $valueToName = [
        self::LEVEL_UNSPECIFIED => 'LEVEL_UNSPECIFIED',
        self::LEVEL_1 => 'LEVEL_1',
        self::LEVEL_2 => 'LEVEL_2',
        self::LEVEL_3 => 'LEVEL_3',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(WvSecurityLevel::class, \VideoWidevineServer\SDK\ProvisionedDeviceInfo_WvSecurityLevel::class);

