<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\LicenseRequest\ContentIdentification;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.ExistingLicense</code>
 */
class ExistingLicense extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification license_id = 1;</code>
     */
    protected $license_id = null;
    /**
     * Generated from protobuf field <code>optional int64 seconds_since_started = 2;</code>
     */
    protected $seconds_since_started = null;
    /**
     * Generated from protobuf field <code>optional int64 seconds_since_last_played = 3;</code>
     */
    protected $seconds_since_last_played = null;
    /**
     * Generated from protobuf field <code>optional bytes session_usage_table_entry = 4;</code>
     */
    protected $session_usage_table_entry = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \VideoWidevineServer\SDK\LicenseIdentification $license_id
     *     @type int|string $seconds_since_started
     *     @type int|string $seconds_since_last_played
     *     @type string $session_usage_table_entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification license_id = 1;</code>
     * @return \VideoWidevineServer\SDK\LicenseIdentification|null
     */
    public function getLicenseId()
    {
        return isset($this->license_id) ? $this->license_id : null;
    }

    public function hasLicenseId()
    {
        return isset($this->license_id);
    }

    public function clearLicenseId()
    {
        unset($this->license_id);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification license_id = 1;</code>
     * @param \VideoWidevineServer\SDK\LicenseIdentification $var
     * @return $this
     */
    public function setLicenseId($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\LicenseIdentification::class);
        $this->license_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 seconds_since_started = 2;</code>
     * @return int|string
     */
    public function getSecondsSinceStarted()
    {
        return isset($this->seconds_since_started) ? $this->seconds_since_started : 0;
    }

    public function hasSecondsSinceStarted()
    {
        return isset($this->seconds_since_started);
    }

    public function clearSecondsSinceStarted()
    {
        unset($this->seconds_since_started);
    }

    /**
     * Generated from protobuf field <code>optional int64 seconds_since_started = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondsSinceStarted($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds_since_started = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 seconds_since_last_played = 3;</code>
     * @return int|string
     */
    public function getSecondsSinceLastPlayed()
    {
        return isset($this->seconds_since_last_played) ? $this->seconds_since_last_played : 0;
    }

    public function hasSecondsSinceLastPlayed()
    {
        return isset($this->seconds_since_last_played);
    }

    public function clearSecondsSinceLastPlayed()
    {
        unset($this->seconds_since_last_played);
    }

    /**
     * Generated from protobuf field <code>optional int64 seconds_since_last_played = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSecondsSinceLastPlayed($var)
    {
        GPBUtil::checkInt64($var);
        $this->seconds_since_last_played = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes session_usage_table_entry = 4;</code>
     * @return string
     */
    public function getSessionUsageTableEntry()
    {
        return isset($this->session_usage_table_entry) ? $this->session_usage_table_entry : '';
    }

    public function hasSessionUsageTableEntry()
    {
        return isset($this->session_usage_table_entry);
    }

    public function clearSessionUsageTableEntry()
    {
        unset($this->session_usage_table_entry);
    }

    /**
     * Generated from protobuf field <code>optional bytes session_usage_table_entry = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionUsageTableEntry($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_usage_table_entry = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ExistingLicense::class, \VideoWidevineServer\SDK\LicenseRequest_ContentIdentification_ExistingLicense::class);

