<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\License\KeyContainer;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.License.KeyContainer.OutputProtection</code>
 */
class OutputProtection extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.HDCP hdcp = 1;</code>
     */
    protected $hdcp = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.CGMS cgms_flags = 2;</code>
     */
    protected $cgms_flags = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $hdcp
     *     @type int $cgms_flags
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.HDCP hdcp = 1;</code>
     * @return int
     */
    public function getHdcp()
    {
        return isset($this->hdcp) ? $this->hdcp : 0;
    }

    public function hasHdcp()
    {
        return isset($this->hdcp);
    }

    public function clearHdcp()
    {
        unset($this->hdcp);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.HDCP hdcp = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setHdcp($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\License\KeyContainer\OutputProtection\HDCP::class);
        $this->hdcp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.CGMS cgms_flags = 2;</code>
     * @return int
     */
    public function getCgmsFlags()
    {
        return isset($this->cgms_flags) ? $this->cgms_flags : 0;
    }

    public function hasCgmsFlags()
    {
        return isset($this->cgms_flags);
    }

    public function clearCgmsFlags()
    {
        unset($this->cgms_flags);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.KeyContainer.OutputProtection.CGMS cgms_flags = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setCgmsFlags($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\License\KeyContainer\OutputProtection\CGMS::class);
        $this->cgms_flags = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(OutputProtection::class, \VideoWidevineServer\SDK\License_KeyContainer_OutputProtection::class);

