<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\ClientIdentification\NameValue instead.
     * @deprecated
     */
    class ClientIdentification_NameValue {}
}
class_exists(ClientIdentification\NameValue::class);
@trigger_error('VideoWidevineServer\SDK\ClientIdentification_NameValue is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\ClientIdentification\NameValue instead', E_USER_DEPRECATED);

