<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientIdentification message used to authenticate the client device.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.ClientIdentification</code>
 */
class ClientIdentification extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of factory-provisioned device root of trust. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.TokenType type = 1;</code>
     */
    protected $type = null;
    /**
     * Factory-provisioned device root of trust. Required.
     *
     * Generated from protobuf field <code>optional bytes token = 2;</code>
     */
    protected $token = null;
    /**
     * Optional client information name/value pairs.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.ClientIdentification.NameValue client_info = 3;</code>
     */
    private $client_info;
    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 4;</code>
     */
    protected $provider_client_token = null;
    /**
     * Number of licenses received by the client to which the token above belongs.
     * Only present if client_token is specified.
     *
     * Generated from protobuf field <code>optional uint32 license_counter = 5;</code>
     */
    protected $license_counter = null;
    /**
     * List of non-baseline client capabilities.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities client_capabilities = 6;</code>
     */
    protected $client_capabilities = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *           Type of factory-provisioned device root of trust. Optional.
     *     @type string $token
     *           Factory-provisioned device root of trust. Required.
     *     @type \VideoWidevineServer\SDK\ClientIdentification\NameValue[]|\Google\Protobuf\Internal\RepeatedField $client_info
     *           Optional client information name/value pairs.
     *     @type string $provider_client_token
     *           Client token generated by the content provider. Optional.
     *     @type int $license_counter
     *           Number of licenses received by the client to which the token above belongs.
     *           Only present if client_token is specified.
     *     @type \VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities $client_capabilities
     *           List of non-baseline client capabilities.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of factory-provisioned device root of trust. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.TokenType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Type of factory-provisioned device root of trust. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.TokenType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\ClientIdentification\TokenType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Factory-provisioned device root of trust. Required.
     *
     * Generated from protobuf field <code>optional bytes token = 2;</code>
     * @return string
     */
    public function getToken()
    {
        return isset($this->token) ? $this->token : '';
    }

    public function hasToken()
    {
        return isset($this->token);
    }

    public function clearToken()
    {
        unset($this->token);
    }

    /**
     * Factory-provisioned device root of trust. Required.
     *
     * Generated from protobuf field <code>optional bytes token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->token = $var;

        return $this;
    }

    /**
     * Optional client information name/value pairs.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.ClientIdentification.NameValue client_info = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientInfo()
    {
        return $this->client_info;
    }

    /**
     * Optional client information name/value pairs.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.ClientIdentification.NameValue client_info = 3;</code>
     * @param \VideoWidevineServer\SDK\ClientIdentification\NameValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \VideoWidevineServer\SDK\ClientIdentification\NameValue::class);
        $this->client_info = $arr;

        return $this;
    }

    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 4;</code>
     * @return string
     */
    public function getProviderClientToken()
    {
        return isset($this->provider_client_token) ? $this->provider_client_token : '';
    }

    public function hasProviderClientToken()
    {
        return isset($this->provider_client_token);
    }

    public function clearProviderClientToken()
    {
        unset($this->provider_client_token);
    }

    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderClientToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->provider_client_token = $var;

        return $this;
    }

    /**
     * Number of licenses received by the client to which the token above belongs.
     * Only present if client_token is specified.
     *
     * Generated from protobuf field <code>optional uint32 license_counter = 5;</code>
     * @return int
     */
    public function getLicenseCounter()
    {
        return isset($this->license_counter) ? $this->license_counter : 0;
    }

    public function hasLicenseCounter()
    {
        return isset($this->license_counter);
    }

    public function clearLicenseCounter()
    {
        unset($this->license_counter);
    }

    /**
     * Number of licenses received by the client to which the token above belongs.
     * Only present if client_token is specified.
     *
     * Generated from protobuf field <code>optional uint32 license_counter = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setLicenseCounter($var)
    {
        GPBUtil::checkUint32($var);
        $this->license_counter = $var;

        return $this;
    }

    /**
     * List of non-baseline client capabilities.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities client_capabilities = 6;</code>
     * @return \VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities|null
     */
    public function getClientCapabilities()
    {
        return isset($this->client_capabilities) ? $this->client_capabilities : null;
    }

    public function hasClientCapabilities()
    {
        return isset($this->client_capabilities);
    }

    public function clearClientCapabilities()
    {
        unset($this->client_capabilities);
    }

    /**
     * List of non-baseline client capabilities.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ClientIdentification.ClientCapabilities client_capabilities = 6;</code>
     * @param \VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities $var
     * @return $this
     */
    public function setClientCapabilities($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities::class);
        $this->client_capabilities = $var;

        return $this;
    }

}

