<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities instead.
     * @deprecated
     */
    class ClientIdentification_ClientCapabilities {}
}
class_exists(ClientIdentification\ClientCapabilities::class);
@trigger_error('VideoWidevineServer\SDK\ClientIdentification_ClientCapabilities is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities instead', E_USER_DEPRECATED);

