<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\ClientIdentification\TokenType instead.
     * @deprecated
     */
    class ClientIdentification_TokenType {}
}
class_exists(ClientIdentification\TokenType::class);
@trigger_error('VideoWidevineServer\SDK\ClientIdentification_TokenType is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\ClientIdentification\TokenType instead', E_USER_DEPRECATED);

