<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities\HdcpVersion instead.
     * @deprecated
     */
    class ClientIdentification_ClientCapabilities_HdcpVersion {}
}
class_exists(ClientIdentification\ClientCapabilities\HdcpVersion::class);
@trigger_error('VideoWidevineServer\SDK\ClientIdentification_ClientCapabilities_HdcpVersion is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\ClientIdentification\ClientCapabilities\HdcpVersion instead', E_USER_DEPRECATED);

