<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * List of DeviceCertificateStatus. Used to propagate certificate revocation and
 * update list.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.DeviceCertificateStatusList</code>
 */
class DeviceCertificateStatusList extends \Google\Protobuf\Internal\Message
{
    /**
     * POSIX time, in seconds, when the list was created. Required.
     *
     * Generated from protobuf field <code>optional uint32 creation_time_seconds = 1;</code>
     */
    protected $creation_time_seconds = null;
    /**
     * DeviceCertificateStatus for each certifificate.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.DeviceCertificateStatus certificate_status = 2;</code>
     */
    private $certificate_status;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $creation_time_seconds
     *           POSIX time, in seconds, when the list was created. Required.
     *     @type \VideoWidevineServer\SDK\DeviceCertificateStatus[]|\Google\Protobuf\Internal\RepeatedField $certificate_status
     *           DeviceCertificateStatus for each certifificate.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * POSIX time, in seconds, when the list was created. Required.
     *
     * Generated from protobuf field <code>optional uint32 creation_time_seconds = 1;</code>
     * @return int
     */
    public function getCreationTimeSeconds()
    {
        return isset($this->creation_time_seconds) ? $this->creation_time_seconds : 0;
    }

    public function hasCreationTimeSeconds()
    {
        return isset($this->creation_time_seconds);
    }

    public function clearCreationTimeSeconds()
    {
        unset($this->creation_time_seconds);
    }

    /**
     * POSIX time, in seconds, when the list was created. Required.
     *
     * Generated from protobuf field <code>optional uint32 creation_time_seconds = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCreationTimeSeconds($var)
    {
        GPBUtil::checkUint32($var);
        $this->creation_time_seconds = $var;

        return $this;
    }

    /**
     * DeviceCertificateStatus for each certifificate.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.DeviceCertificateStatus certificate_status = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificateStatus()
    {
        return $this->certificate_status;
    }

    /**
     * DeviceCertificateStatus for each certifificate.
     *
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.DeviceCertificateStatus certificate_status = 2;</code>
     * @param \VideoWidevineServer\SDK\DeviceCertificateStatus[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificateStatus($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \VideoWidevineServer\SDK\DeviceCertificateStatus::class);
        $this->certificate_status = $arr;

        return $this;
    }

}

