<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains the status of the root or an intermediate DeviceCertificate.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.DeviceCertificateStatus</code>
 */
class DeviceCertificateStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Serial number of the DeviceCertificate to which this message refers.
     * Required.
     *
     * Generated from protobuf field <code>optional bytes serial_number = 1;</code>
     */
    protected $serial_number = null;
    /**
     * Status of the certificate. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.DeviceCertificateStatus.CertificateStatus status = 2;</code>
     */
    protected $status = null;
    /**
     * Device model information about the device to which the certificate
     * corresponds. Required.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo device_info = 4;</code>
     */
    protected $device_info = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $serial_number
     *           Serial number of the DeviceCertificate to which this message refers.
     *           Required.
     *     @type int $status
     *           Status of the certificate. Optional.
     *     @type \VideoWidevineServer\SDK\ProvisionedDeviceInfo $device_info
     *           Device model information about the device to which the certificate
     *           corresponds. Required.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Serial number of the DeviceCertificate to which this message refers.
     * Required.
     *
     * Generated from protobuf field <code>optional bytes serial_number = 1;</code>
     * @return string
     */
    public function getSerialNumber()
    {
        return isset($this->serial_number) ? $this->serial_number : '';
    }

    public function hasSerialNumber()
    {
        return isset($this->serial_number);
    }

    public function clearSerialNumber()
    {
        unset($this->serial_number);
    }

    /**
     * Serial number of the DeviceCertificate to which this message refers.
     * Required.
     *
     * Generated from protobuf field <code>optional bytes serial_number = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSerialNumber($var)
    {
        GPBUtil::checkString($var, False);
        $this->serial_number = $var;

        return $this;
    }

    /**
     * Status of the certificate. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.DeviceCertificateStatus.CertificateStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return isset($this->status) ? $this->status : 0;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Status of the certificate. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.DeviceCertificateStatus.CertificateStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\DeviceCertificateStatus\CertificateStatus::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Device model information about the device to which the certificate
     * corresponds. Required.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo device_info = 4;</code>
     * @return \VideoWidevineServer\SDK\ProvisionedDeviceInfo|null
     */
    public function getDeviceInfo()
    {
        return isset($this->device_info) ? $this->device_info : null;
    }

    public function hasDeviceInfo()
    {
        return isset($this->device_info);
    }

    public function clearDeviceInfo()
    {
        unset($this->device_info);
    }

    /**
     * Device model information about the device to which the certificate
     * corresponds. Required.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo device_info = 4;</code>
     * @param \VideoWidevineServer\SDK\ProvisionedDeviceInfo $var
     * @return $this
     */
    public function setDeviceInfo($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\ProvisionedDeviceInfo::class);
        $this->device_info = $var;

        return $this;
    }

}

