<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\DeviceCertificateStatus\CertificateStatus instead.
     * @deprecated
     */
    class DeviceCertificateStatus_CertificateStatus {}
}
class_exists(DeviceCertificateStatus\CertificateStatus::class);
@trigger_error('VideoWidevineServer\SDK\DeviceCertificateStatus_CertificateStatus is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\DeviceCertificateStatus\CertificateStatus instead', E_USER_DEPRECATED);

