<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\DeviceCertificate\CertificateType instead.
     * @deprecated
     */
    class DeviceCertificate_CertificateType {}
}
class_exists(DeviceCertificate\CertificateType::class);
@trigger_error('VideoWidevineServer\SDK\DeviceCertificate_CertificateType is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\DeviceCertificate\CertificateType instead', E_USER_DEPRECATED);

