<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\License\Policy instead.
     * @deprecated
     */
    class License_Policy {}
}
class_exists(License\Policy::class);
@trigger_error('VideoWidevineServer\SDK\License_Policy is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\License\Policy instead', E_USER_DEPRECATED);

