<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\License\KeyContainer\SecurityLevel instead.
     * @deprecated
     */
    class License_KeyContainer_SecurityLevel {}
}
class_exists(License\KeyContainer\SecurityLevel::class);
@trigger_error('VideoWidevineServer\SDK\License_KeyContainer_SecurityLevel is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\License\KeyContainer\SecurityLevel instead', E_USER_DEPRECATED);

