<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\License\KeyContainer\OutputProtection\HDCP instead.
     * @deprecated
     */
    class License_KeyContainer_OutputProtection_HDCP {}
}
class_exists(License\KeyContainer\OutputProtection\HDCP::class);
@trigger_error('VideoWidevineServer\SDK\License_KeyContainer_OutputProtection_HDCP is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\License\KeyContainer\OutputProtection\HDCP instead', E_USER_DEPRECATED);

