<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\LicenseRequest\RequestType instead.
     * @deprecated
     */
    class LicenseRequest_RequestType {}
}
class_exists(LicenseRequest\RequestType::class);
@trigger_error('VideoWidevineServer\SDK\LicenseRequest_RequestType is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\LicenseRequest\RequestType instead', E_USER_DEPRECATED);

