<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\LicenseError\Error instead.
     * @deprecated
     */
    class LicenseError_Error {}
}
class_exists(LicenseError\Error::class);
@trigger_error('VideoWidevineServer\SDK\LicenseError_Error is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\LicenseError\Error instead', E_USER_DEPRECATED);

