<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\LicenseRequest\ContentIdentification instead.
     * @deprecated
     */
    class LicenseRequest_ContentIdentification {}
}
class_exists(LicenseRequest\ContentIdentification::class);
@trigger_error('VideoWidevineServer\SDK\LicenseRequest_ContentIdentification is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\LicenseRequest\ContentIdentification instead', E_USER_DEPRECATED);

