<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.License</code>
 */
class License extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification id = 1;</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.Policy policy = 2;</code>
     */
    protected $policy = null;
    /**
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.License.KeyContainer key = 3;</code>
     */
    private $key;
    /**
     * Generated from protobuf field <code>optional int64 license_start_time = 4;</code>
     */
    protected $license_start_time = null;
    /**
     * Generated from protobuf field <code>optional bool remote_attestation_verified = 5;</code>
     */
    protected $remote_attestation_verified = null;
    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 6;</code>
     */
    protected $provider_client_token = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \VideoWidevineServer\SDK\LicenseIdentification $id
     *     @type \VideoWidevineServer\SDK\License\Policy $policy
     *     @type \VideoWidevineServer\SDK\License\KeyContainer[]|\Google\Protobuf\Internal\RepeatedField $key
     *     @type int|string $license_start_time
     *     @type bool $remote_attestation_verified
     *     @type string $provider_client_token
     *           Client token generated by the content provider. Optional.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification id = 1;</code>
     * @return \VideoWidevineServer\SDK\LicenseIdentification|null
     */
    public function getId()
    {
        return isset($this->id) ? $this->id : null;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseIdentification id = 1;</code>
     * @param \VideoWidevineServer\SDK\LicenseIdentification $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\LicenseIdentification::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.Policy policy = 2;</code>
     * @return \VideoWidevineServer\SDK\License\Policy|null
     */
    public function getPolicy()
    {
        return isset($this->policy) ? $this->policy : null;
    }

    public function hasPolicy()
    {
        return isset($this->policy);
    }

    public function clearPolicy()
    {
        unset($this->policy);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.License.Policy policy = 2;</code>
     * @param \VideoWidevineServer\SDK\License\Policy $var
     * @return $this
     */
    public function setPolicy($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\License\Policy::class);
        $this->policy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.License.KeyContainer key = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>repeated .VideoWidevineServer.SDK.License.KeyContainer key = 3;</code>
     * @param \VideoWidevineServer\SDK\License\KeyContainer[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKey($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \VideoWidevineServer\SDK\License\KeyContainer::class);
        $this->key = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 license_start_time = 4;</code>
     * @return int|string
     */
    public function getLicenseStartTime()
    {
        return isset($this->license_start_time) ? $this->license_start_time : 0;
    }

    public function hasLicenseStartTime()
    {
        return isset($this->license_start_time);
    }

    public function clearLicenseStartTime()
    {
        unset($this->license_start_time);
    }

    /**
     * Generated from protobuf field <code>optional int64 license_start_time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLicenseStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->license_start_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool remote_attestation_verified = 5;</code>
     * @return bool
     */
    public function getRemoteAttestationVerified()
    {
        return isset($this->remote_attestation_verified) ? $this->remote_attestation_verified : false;
    }

    public function hasRemoteAttestationVerified()
    {
        return isset($this->remote_attestation_verified);
    }

    public function clearRemoteAttestationVerified()
    {
        unset($this->remote_attestation_verified);
    }

    /**
     * Generated from protobuf field <code>optional bool remote_attestation_verified = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setRemoteAttestationVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->remote_attestation_verified = $var;

        return $this;
    }

    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 6;</code>
     * @return string
     */
    public function getProviderClientToken()
    {
        return isset($this->provider_client_token) ? $this->provider_client_token : '';
    }

    public function hasProviderClientToken()
    {
        return isset($this->provider_client_token);
    }

    public function clearProviderClientToken()
    {
        unset($this->provider_client_token);
    }

    /**
     * Client token generated by the content provider. Optional.
     *
     * Generated from protobuf field <code>optional bytes provider_client_token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderClientToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->provider_client_token = $var;

        return $this;
    }

}

