<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC instead.
     * @deprecated
     */
    class LicenseRequest_ContentIdentification_CENC {}
}
class_exists(LicenseRequest\ContentIdentification\CENC::class);
@trigger_error('VideoWidevineServer\SDK\LicenseRequest_ContentIdentification_CENC is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC instead', E_USER_DEPRECATED);

