<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use UnexpectedValueException;

/**
 * Protobuf type <code>VideoWidevineServer.SDK.LicenseType</code>
 */
class LicenseType
{
    /**
     * Generated from protobuf enum <code>LICENSETYPE_UNKNOWN = 0;</code>
     */
    const LICENSETYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>STREAMING = 1;</code>
     */
    const STREAMING = 1;
    /**
     * Generated from protobuf enum <code>OFFLINE = 2;</code>
     */
    const OFFLINE = 2;

    private static $valueToName = [
        self::LICENSETYPE_UNKNOWN => 'LICENSETYPE_UNKNOWN',
        self::STREAMING => 'STREAMING',
        self::OFFLINE => 'OFFLINE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

