<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * LicenseIdentification is propagated from LicenseRequest to License,
 * incrementing version with each iteration.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.LicenseIdentification</code>
 */
class LicenseIdentification extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bytes request_id = 1;</code>
     */
    protected $request_id = null;
    /**
     * Generated from protobuf field <code>optional bytes session_id = 2;</code>
     */
    protected $session_id = null;
    /**
     * Generated from protobuf field <code>optional bytes purchase_id = 3;</code>
     */
    protected $purchase_id = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseType type = 4;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     */
    protected $version = null;
    /**
     * Generated from protobuf field <code>optional bytes provider_session_token = 6;</code>
     */
    protected $provider_session_token = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $request_id
     *     @type string $session_id
     *     @type string $purchase_id
     *     @type int $type
     *     @type int $version
     *     @type string $provider_session_token
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bytes request_id = 1;</code>
     * @return string
     */
    public function getRequestId()
    {
        return isset($this->request_id) ? $this->request_id : '';
    }

    public function hasRequestId()
    {
        return isset($this->request_id);
    }

    public function clearRequestId()
    {
        unset($this->request_id);
    }

    /**
     * Generated from protobuf field <code>optional bytes request_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, False);
        $this->request_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes session_id = 2;</code>
     * @return string
     */
    public function getSessionId()
    {
        return isset($this->session_id) ? $this->session_id : '';
    }

    public function hasSessionId()
    {
        return isset($this->session_id);
    }

    public function clearSessionId()
    {
        unset($this->session_id);
    }

    /**
     * Generated from protobuf field <code>optional bytes session_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes purchase_id = 3;</code>
     * @return string
     */
    public function getPurchaseId()
    {
        return isset($this->purchase_id) ? $this->purchase_id : '';
    }

    public function hasPurchaseId()
    {
        return isset($this->purchase_id);
    }

    public function clearPurchaseId()
    {
        unset($this->purchase_id);
    }

    /**
     * Generated from protobuf field <code>optional bytes purchase_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPurchaseId($var)
    {
        GPBUtil::checkString($var, False);
        $this->purchase_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseType type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseType type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\LicenseType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     * @return int
     */
    public function getVersion()
    {
        return isset($this->version) ? $this->version : 0;
    }

    public function hasVersion()
    {
        return isset($this->version);
    }

    public function clearVersion()
    {
        unset($this->version);
    }

    /**
     * Generated from protobuf field <code>optional int32 version = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt32($var);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes provider_session_token = 6;</code>
     * @return string
     */
    public function getProviderSessionToken()
    {
        return isset($this->provider_session_token) ? $this->provider_session_token : '';
    }

    public function hasProviderSessionToken()
    {
        return isset($this->provider_session_token);
    }

    public function clearProviderSessionToken()
    {
        unset($this->provider_session_token);
    }

    /**
     * Generated from protobuf field <code>optional bytes provider_session_token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setProviderSessionToken($var)
    {
        GPBUtil::checkString($var, False);
        $this->provider_session_token = $var;

        return $this;
    }

}

