<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.LicenseError</code>
 */
class LicenseError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseError.Error error_code = 1;</code>
     */
    protected $error_code = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_code
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseError.Error error_code = 1;</code>
     * @return int
     */
    public function getErrorCode()
    {
        return isset($this->error_code) ? $this->error_code : 0;
    }

    public function hasErrorCode()
    {
        return isset($this->error_code);
    }

    public function clearErrorCode()
    {
        unset($this->error_code);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseError.Error error_code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\LicenseError\Error::class);
        $this->error_code = $var;

        return $this;
    }

}

