<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\License\KeyContainer\OutputProtection instead.
     * @deprecated
     */
    class License_KeyContainer_OutputProtection {}
}
class_exists(License\KeyContainer\OutputProtection::class);
@trigger_error('VideoWidevineServer\SDK\License_KeyContainer_OutputProtection is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\License\KeyContainer\OutputProtection instead', E_USER_DEPRECATED);

