<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\ProvisionedDeviceInfo\WvSecurityLevel instead.
     * @deprecated
     */
    class ProvisionedDeviceInfo_WvSecurityLevel {}
}
class_exists(ProvisionedDeviceInfo\WvSecurityLevel::class);
@trigger_error('VideoWidevineServer\SDK\ProvisionedDeviceInfo_WvSecurityLevel is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\ProvisionedDeviceInfo\WvSecurityLevel instead', E_USER_DEPRECATED);

