<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Contains device model information for a provisioned device.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.ProvisionedDeviceInfo</code>
 */
class ProvisionedDeviceInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Widevine system ID for the device. Mandatory.
     *
     * Generated from protobuf field <code>optional uint32 system_id = 1;</code>
     */
    protected $system_id = null;
    /**
     * Name of system-on-a-chip. Optional.
     *
     * Generated from protobuf field <code>optional string soc = 2;</code>
     */
    protected $soc = null;
    /**
     * Name of manufacturer. Optional.
     *
     * Generated from protobuf field <code>optional string manufacturer = 3;</code>
     */
    protected $manufacturer = null;
    /**
     * Manufacturer's model name. Matches "brand" in device metadata. Optional.
     *
     * Generated from protobuf field <code>optional string model = 4;</code>
     */
    protected $model = null;
    /**
     * Type of device (Phone, Tablet, TV, etc).
     *
     * Generated from protobuf field <code>optional string device_type = 5;</code>
     */
    protected $device_type = null;
    /**
     * Device model year. Optional.
     *
     * Generated from protobuf field <code>optional uint32 model_year = 6;</code>
     */
    protected $model_year = null;
    /**
     * Widevine-defined security level. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo.WvSecurityLevel security_level = 7;</code>
     */
    protected $security_level = null;
    /**
     * True if the certificate corresponds to a test (non production) device.
     * Optional.
     *
     * Generated from protobuf field <code>optional bool test_device = 8;</code>
     */
    protected $test_device = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $system_id
     *           Widevine system ID for the device. Mandatory.
     *     @type string $soc
     *           Name of system-on-a-chip. Optional.
     *     @type string $manufacturer
     *           Name of manufacturer. Optional.
     *     @type string $model
     *           Manufacturer's model name. Matches "brand" in device metadata. Optional.
     *     @type string $device_type
     *           Type of device (Phone, Tablet, TV, etc).
     *     @type int $model_year
     *           Device model year. Optional.
     *     @type int $security_level
     *           Widevine-defined security level. Optional.
     *     @type bool $test_device
     *           True if the certificate corresponds to a test (non production) device.
     *           Optional.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Widevine system ID for the device. Mandatory.
     *
     * Generated from protobuf field <code>optional uint32 system_id = 1;</code>
     * @return int
     */
    public function getSystemId()
    {
        return isset($this->system_id) ? $this->system_id : 0;
    }

    public function hasSystemId()
    {
        return isset($this->system_id);
    }

    public function clearSystemId()
    {
        unset($this->system_id);
    }

    /**
     * Widevine system ID for the device. Mandatory.
     *
     * Generated from protobuf field <code>optional uint32 system_id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSystemId($var)
    {
        GPBUtil::checkUint32($var);
        $this->system_id = $var;

        return $this;
    }

    /**
     * Name of system-on-a-chip. Optional.
     *
     * Generated from protobuf field <code>optional string soc = 2;</code>
     * @return string
     */
    public function getSoc()
    {
        return isset($this->soc) ? $this->soc : '';
    }

    public function hasSoc()
    {
        return isset($this->soc);
    }

    public function clearSoc()
    {
        unset($this->soc);
    }

    /**
     * Name of system-on-a-chip. Optional.
     *
     * Generated from protobuf field <code>optional string soc = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSoc($var)
    {
        GPBUtil::checkString($var, True);
        $this->soc = $var;

        return $this;
    }

    /**
     * Name of manufacturer. Optional.
     *
     * Generated from protobuf field <code>optional string manufacturer = 3;</code>
     * @return string
     */
    public function getManufacturer()
    {
        return isset($this->manufacturer) ? $this->manufacturer : '';
    }

    public function hasManufacturer()
    {
        return isset($this->manufacturer);
    }

    public function clearManufacturer()
    {
        unset($this->manufacturer);
    }

    /**
     * Name of manufacturer. Optional.
     *
     * Generated from protobuf field <code>optional string manufacturer = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setManufacturer($var)
    {
        GPBUtil::checkString($var, True);
        $this->manufacturer = $var;

        return $this;
    }

    /**
     * Manufacturer's model name. Matches "brand" in device metadata. Optional.
     *
     * Generated from protobuf field <code>optional string model = 4;</code>
     * @return string
     */
    public function getModel()
    {
        return isset($this->model) ? $this->model : '';
    }

    public function hasModel()
    {
        return isset($this->model);
    }

    public function clearModel()
    {
        unset($this->model);
    }

    /**
     * Manufacturer's model name. Matches "brand" in device metadata. Optional.
     *
     * Generated from protobuf field <code>optional string model = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setModel($var)
    {
        GPBUtil::checkString($var, True);
        $this->model = $var;

        return $this;
    }

    /**
     * Type of device (Phone, Tablet, TV, etc).
     *
     * Generated from protobuf field <code>optional string device_type = 5;</code>
     * @return string
     */
    public function getDeviceType()
    {
        return isset($this->device_type) ? $this->device_type : '';
    }

    public function hasDeviceType()
    {
        return isset($this->device_type);
    }

    public function clearDeviceType()
    {
        unset($this->device_type);
    }

    /**
     * Type of device (Phone, Tablet, TV, etc).
     *
     * Generated from protobuf field <code>optional string device_type = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setDeviceType($var)
    {
        GPBUtil::checkString($var, True);
        $this->device_type = $var;

        return $this;
    }

    /**
     * Device model year. Optional.
     *
     * Generated from protobuf field <code>optional uint32 model_year = 6;</code>
     * @return int
     */
    public function getModelYear()
    {
        return isset($this->model_year) ? $this->model_year : 0;
    }

    public function hasModelYear()
    {
        return isset($this->model_year);
    }

    public function clearModelYear()
    {
        unset($this->model_year);
    }

    /**
     * Device model year. Optional.
     *
     * Generated from protobuf field <code>optional uint32 model_year = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setModelYear($var)
    {
        GPBUtil::checkUint32($var);
        $this->model_year = $var;

        return $this;
    }

    /**
     * Widevine-defined security level. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo.WvSecurityLevel security_level = 7;</code>
     * @return int
     */
    public function getSecurityLevel()
    {
        return isset($this->security_level) ? $this->security_level : 0;
    }

    public function hasSecurityLevel()
    {
        return isset($this->security_level);
    }

    public function clearSecurityLevel()
    {
        unset($this->security_level);
    }

    /**
     * Widevine-defined security level. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.ProvisionedDeviceInfo.WvSecurityLevel security_level = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setSecurityLevel($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\ProvisionedDeviceInfo\WvSecurityLevel::class);
        $this->security_level = $var;

        return $this;
    }

    /**
     * True if the certificate corresponds to a test (non production) device.
     * Optional.
     *
     * Generated from protobuf field <code>optional bool test_device = 8;</code>
     * @return bool
     */
    public function getTestDevice()
    {
        return isset($this->test_device) ? $this->test_device : false;
    }

    public function hasTestDevice()
    {
        return isset($this->test_device);
    }

    public function clearTestDevice()
    {
        unset($this->test_device);
    }

    /**
     * True if the certificate corresponds to a test (non production) device.
     * Optional.
     *
     * Generated from protobuf field <code>optional bool test_device = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setTestDevice($var)
    {
        GPBUtil::checkBool($var);
        $this->test_device = $var;

        return $this;
    }

}

