<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

if (false) {
    /**
     * This class is deprecated. Use VideoWidevineServer\SDK\SignedMessage\MessageType instead.
     * @deprecated
     */
    class SignedMessage_MessageType {}
}
class_exists(SignedMessage\MessageType::class);
@trigger_error('VideoWidevineServer\SDK\SignedMessage_MessageType is deprecated and will be removed in the next major release. Use VideoWidevineServer\SDK\SignedMessage\MessageType instead', E_USER_DEPRECATED);

