<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.SignedMessage</code>
 */
class SignedMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.SignedMessage.MessageType type = 1;</code>
     */
    protected $type = null;
    /**
     * Generated from protobuf field <code>optional bytes msg = 2;</code>
     */
    protected $msg = null;
    /**
     * Generated from protobuf field <code>optional bytes signature = 3;</code>
     */
    protected $signature = null;
    /**
     * Generated from protobuf field <code>optional bytes session_key = 4;</code>
     */
    protected $session_key = null;
    /**
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.RemoteAttestation remote_attestation = 5;</code>
     */
    protected $remote_attestation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type string $msg
     *     @type string $signature
     *     @type string $session_key
     *     @type \VideoWidevineServer\SDK\RemoteAttestation $remote_attestation
     *           Remote attestation data which will be present in the initial license
     *           request for ChromeOS client devices operating in verified mode. Remote
     *           attestation challenge data is |msg| field above. Optional.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.SignedMessage.MessageType type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : 0;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.SignedMessage.MessageType type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \VideoWidevineServer\SDK\SignedMessage\MessageType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return isset($this->msg) ? $this->msg : '';
    }

    public function hasMsg()
    {
        return isset($this->msg);
    }

    public function clearMsg()
    {
        unset($this->msg);
    }

    /**
     * Generated from protobuf field <code>optional bytes msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, False);
        $this->msg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes signature = 3;</code>
     * @return string
     */
    public function getSignature()
    {
        return isset($this->signature) ? $this->signature : '';
    }

    public function hasSignature()
    {
        return isset($this->signature);
    }

    public function clearSignature()
    {
        unset($this->signature);
    }

    /**
     * Generated from protobuf field <code>optional bytes signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bytes session_key = 4;</code>
     * @return string
     */
    public function getSessionKey()
    {
        return isset($this->session_key) ? $this->session_key : '';
    }

    public function hasSessionKey()
    {
        return isset($this->session_key);
    }

    public function clearSessionKey()
    {
        unset($this->session_key);
    }

    /**
     * Generated from protobuf field <code>optional bytes session_key = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSessionKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->session_key = $var;

        return $this;
    }

    /**
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.RemoteAttestation remote_attestation = 5;</code>
     * @return \VideoWidevineServer\SDK\RemoteAttestation|null
     */
    public function getRemoteAttestation()
    {
        return isset($this->remote_attestation) ? $this->remote_attestation : null;
    }

    public function hasRemoteAttestation()
    {
        return isset($this->remote_attestation);
    }

    public function clearRemoteAttestation()
    {
        unset($this->remote_attestation);
    }

    /**
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.RemoteAttestation remote_attestation = 5;</code>
     * @param \VideoWidevineServer\SDK\RemoteAttestation $var
     * @return $this
     */
    public function setRemoteAttestation($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\RemoteAttestation::class);
        $this->remote_attestation = $var;

        return $this;
    }

}

