<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Serialized ProvisioningRequest or ProvisioningResponse signed with
 * The message authentication key.
 *
 * Generated from protobuf message <code>VideoWidevineServer.SDK.SignedProvisioningMessage</code>
 */
class SignedProvisioningMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Serialized ProvisioningRequest or ProvisioningResponse. Required.
     *
     * Generated from protobuf field <code>optional bytes message = 1;</code>
     */
    protected $message = null;
    /**
     * HMAC-SHA256 signature of message. Required.
     *
     * Generated from protobuf field <code>optional bytes signature = 2;</code>
     */
    protected $signature = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $message
     *           Serialized ProvisioningRequest or ProvisioningResponse. Required.
     *     @type string $signature
     *           HMAC-SHA256 signature of message. Required.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Serialized ProvisioningRequest or ProvisioningResponse. Required.
     *
     * Generated from protobuf field <code>optional bytes message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return isset($this->message) ? $this->message : '';
    }

    public function hasMessage()
    {
        return isset($this->message);
    }

    public function clearMessage()
    {
        unset($this->message);
    }

    /**
     * Serialized ProvisioningRequest or ProvisioningResponse. Required.
     *
     * Generated from protobuf field <code>optional bytes message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, False);
        $this->message = $var;

        return $this;
    }

    /**
     * HMAC-SHA256 signature of message. Required.
     *
     * Generated from protobuf field <code>optional bytes signature = 2;</code>
     * @return string
     */
    public function getSignature()
    {
        return isset($this->signature) ? $this->signature : '';
    }

    public function hasSignature()
    {
        return isset($this->signature);
    }

    public function clearSignature()
    {
        unset($this->signature);
    }

    /**
     * HMAC-SHA256 signature of message. Required.
     *
     * Generated from protobuf field <code>optional bytes signature = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

