<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\LicenseRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>VideoWidevineServer.SDK.LicenseRequest.ContentIdentification</code>
 */
class ContentIdentification extends \Google\Protobuf\Internal\Message
{
    /**
     * Exactly one of these must be present.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.CENC cenc_id = 1;</code>
     */
    protected $cenc_id = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.WebM webm_id = 2;</code>
     */
    protected $webm_id = null;
    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.ExistingLicense license = 3;</code>
     */
    protected $license = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC $cenc_id
     *           Exactly one of these must be present.
     *     @type \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\WebM $webm_id
     *     @type \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\ExistingLicense $license
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\LicenseProtocol::initOnce();
        parent::__construct($data);
    }

    /**
     * Exactly one of these must be present.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.CENC cenc_id = 1;</code>
     * @return \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC|null
     */
    public function getCencId()
    {
        return isset($this->cenc_id) ? $this->cenc_id : null;
    }

    public function hasCencId()
    {
        return isset($this->cenc_id);
    }

    public function clearCencId()
    {
        unset($this->cenc_id);
    }

    /**
     * Exactly one of these must be present.
     *
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.CENC cenc_id = 1;</code>
     * @param \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC $var
     * @return $this
     */
    public function setCencId($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\CENC::class);
        $this->cenc_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.WebM webm_id = 2;</code>
     * @return \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\WebM|null
     */
    public function getWebmId()
    {
        return isset($this->webm_id) ? $this->webm_id : null;
    }

    public function hasWebmId()
    {
        return isset($this->webm_id);
    }

    public function clearWebmId()
    {
        unset($this->webm_id);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.WebM webm_id = 2;</code>
     * @param \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\WebM $var
     * @return $this
     */
    public function setWebmId($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\WebM::class);
        $this->webm_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.ExistingLicense license = 3;</code>
     * @return \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\ExistingLicense|null
     */
    public function getLicense()
    {
        return isset($this->license) ? $this->license : null;
    }

    public function hasLicense()
    {
        return isset($this->license);
    }

    public function clearLicense()
    {
        unset($this->license);
    }

    /**
     * Generated from protobuf field <code>optional .VideoWidevineServer.SDK.LicenseRequest.ContentIdentification.ExistingLicense license = 3;</code>
     * @param \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\ExistingLicense $var
     * @return $this
     */
    public function setLicense($var)
    {
        GPBUtil::checkMessage($var, \VideoWidevineServer\SDK\LicenseRequest\ContentIdentification\ExistingLicense::class);
        $this->license = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ContentIdentification::class, \VideoWidevineServer\SDK\LicenseRequest_ContentIdentification::class);

