<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: license_protocol.proto

namespace VideoWidevineServer\SDK\LicenseRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>VideoWidevineServer.SDK.LicenseRequest.RequestType</code>
 */
class RequestType
{
    /**
     * Generated from protobuf enum <code>REQUESTYPE_UNKNOWN = 0;</code>
     */
    const REQUESTYPE_UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>NEW = 1;</code>
     */
    const PBNEW = 1;
    /**
     * Generated from protobuf enum <code>RENEWAL = 2;</code>
     */
    const RENEWAL = 2;
    /**
     * Generated from protobuf enum <code>RELEASE = 3;</code>
     */
    const RELEASE = 3;

    private static $valueToName = [
        self::REQUESTYPE_UNKNOWN => 'REQUESTYPE_UNKNOWN',
        self::PBNEW => 'PBNEW',
        self::RENEWAL => 'RENEWAL',
        self::RELEASE => 'RELEASE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RequestType::class, \VideoWidevineServer\SDK\LicenseRequest_RequestType::class);

